services:
  qbittorrent:
    image: "linuxserver/qbittorrent"
    container_name: qbittorrent
    ports:
      - "8080:8080"
    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - QBITTORRENT_WEBUI_ADMIN_USER=admin
      - QBITTORRENT_WEBUI_ADMIN_PASS=yourpassword
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  sonarr:
    image: "sonarr/sonarr:latest"
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - SONARR_URL=http://sonarr:8989
    volumes:
      - ./sonarr/config:/config
      - ./downloads:/downloads
      - ./tv:/tv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  radarr:
    image: "radarr/radarr:latest"
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - RADARR_URL=http://radarr:7878
    volumes:
      - ./radarr/config:/config
      - ./downloads:/downloads
      - ./movies:/movies
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  default:
    external:
      name: my_network
