version: '3.8' # Updated to a more recent version
services:
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=supersecret
    # Warning: Avoid using default credentials in production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    # Extension Policy Configuration
    extension: 
      enabled: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 

# Additional documentation and organization
# This is a production-ready configuration with improved security practices and resource limits.