name: Build & Publish Development Docker Image

on:
  # Automatically build on pushes to develop branch
  push:
    branches: [ develop ]
    paths:
      - "Dockerfile"
      - "src/**"
      - ".github/workflows/develop-build.yml"
  # Also allow manual runs
  workflow_dispatch:
    inputs:
      extra_tag:
        description: "Optional extra tag to publish (e.g. 1.0.0-beta1)"
        required: false
        type: string

permissions:
  contents: write
  packages: write

concurrency:
  group: docker-dev-publish-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: qbit-guard

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate dev version with timestamp
        id: version
        run: |
          # Get the current timestamp in a format suitable for versioning
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          
          # Create a proper version string for the dev build
          VERSION="0.0.0-dev.${TIMESTAMP}"
          
          echo "build_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare tags
        id: prep
        run: |
          REPO="ghcr.io/${{ github.repository_owner | tr '[:upper:]' '[:lower:]' }}/${{ env.IMAGE_NAME }}"
          VERSION="${{ steps.version.outputs.build_version }}"
          
          # Define tags explicitly
          TAGS="${REPO}:dev"
          TAGS="${TAGS},${REPO}:${VERSION}"
          TAGS="${TAGS},${REPO}:develop"
          TAGS="${TAGS},${REPO}:sha-${GITHUB_SHA::8}"
          
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "repo=${REPO}" >> $GITHUB_OUTPUT

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_VERSION=${{ steps.version.outputs.build_version }}

      - name: Push extra tag (from workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.extra_tag != '' }}
        run: |
          REPO="${{ steps.prep.outputs.repo }}"
          docker buildx imagetools create -t "${REPO}:${{ inputs.extra_tag }}" "${REPO}:dev"